// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1aZxfdV097InvkGZ15Vr76WGxJr0aE8',
    appId: '1:1074299395333:web:ac5bb865e50ab036edeb6c',
    messagingSenderId: '1074299395333',
    projectId: 'reclaim-f1b3f',
    authDomain: 'reclaim-f1b3f.firebaseapp.com',
    storageBucket: 'reclaim-f1b3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5yzAWBVDjgvlRljmYp37jPuK_0GT5GFs',
    appId: '1:1074299395333:android:5cf16f4d23bfe517edeb6c',
    messagingSenderId: '1074299395333',
    projectId: 'reclaim-f1b3f',
    storageBucket: 'reclaim-f1b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnbgQNGb5mN_gYjZq7oi4DR4KD3mzVtFQ',
    appId: '1:1074299395333:ios:7fd78ba3dfb2e73aedeb6c',
    messagingSenderId: '1074299395333',
    projectId: 'reclaim-f1b3f',
    storageBucket: 'reclaim-f1b3f.firebasestorage.app',
    iosBundleId: 'com.example.recalim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnbgQNGb5mN_gYjZq7oi4DR4KD3mzVtFQ',
    appId: '1:1074299395333:ios:7fd78ba3dfb2e73aedeb6c',
    messagingSenderId: '1074299395333',
    projectId: 'reclaim-f1b3f',
    storageBucket: 'reclaim-f1b3f.firebasestorage.app',
    iosBundleId: 'com.example.recalim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE1aZxfdV097InvkGZ15Vr76WGxJr0aE8',
    appId: '1:1074299395333:web:338e97532c5cceb1edeb6c',
    messagingSenderId: '1074299395333',
    projectId: 'reclaim-f1b3f',
    authDomain: 'reclaim-f1b3f.firebaseapp.com',
    storageBucket: 'reclaim-f1b3f.firebasestorage.app',
  );
}
